/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import classes.Animal;
import classes.Tutor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FormAnimais extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAnimais.class.getName());
    ArrayList<Animal> listaAnimais;
    ArrayList<Tutor> listaTutores;;    
    
    private Tutor buscarTutor(int codTutor){
        for(Tutor t : listaTutores){
            if (t.getIdTutor() == codTutor){
                return t;
            }
        }
        return null;
    }
    
    private Animal buscarAnimal(int codPet) {
        for (Animal a : listaAnimais) {
            if (a.getIdAnimal() == codPet) {
                return a;
            }
        }
        return null;
    }
    
    public FormAnimais(java.awt.Frame parent, boolean modal, ArrayList<Animal> listaAnimais, ArrayList<Tutor> listaTutores) {
        super(parent, modal);
        this.listaAnimais = listaAnimais;
        this.listaTutores = listaTutores;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarAnimal = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        btnListarAnimais = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCadastrarAnimal.setText("Inserir Animal");
        btnCadastrarAnimal.addActionListener(this::btnCadastrarAnimalActionPerformed);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        btnListarAnimais.setText("Listar Animais");
        btnListarAnimais.addActionListener(this::btnListarAnimaisActionPerformed);

        jButton1.setText("Excluir Animal");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Alterar Animal");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarAnimais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrarAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarAnimais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAnimalActionPerformed
        int codigo = 1 + listaAnimais.size();
        
        int codTutor = Integer.parseInt(JOptionPane.showInputDialog("Insira o código do tutor: "));
        Tutor tutor = buscarTutor(codTutor);
        
        if (tutor == null) {
            JOptionPane.showMessageDialog(null, "Tutor inexistente!");
        } else {
            Object[] opcoes = {"Macho", "Fêmea"};
            String nome = JOptionPane.showInputDialog("Insira o Nome do Pet: ");
            int intSexo = JOptionPane.showOptionDialog(
                    null,
                    "Selecione o Sexo do animal",
                    "Sexo",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opcoes,
                    opcoes[0]);
            
            String especie = JOptionPane.showInputDialog("Insira a espécie do animal");
            String raca = JOptionPane.showInputDialog("Insira a raça do animal");
            String dataNascimento = JOptionPane.showInputDialog("Insira a data de nascimento do animal");
            double peso = Double.parseDouble(JOptionPane.showInputDialog("Insira o peso do animal"));
            
            String sexo = "";
            
            switch(intSexo){
                case 0:
                    sexo = "Macho";
                    break;
                case 1:
                    sexo = "Fêmea";
                    break;
                case -1:
                    sexo = "Não informado";
                    break;
            }
            
            listaAnimais.add(new Animal(codigo, nome, especie, raca, sexo, dataNascimento, peso, tutor));
            taSaida.setText("Animal inserido com sucesso");
            
        }
        
    }//GEN-LAST:event_btnCadastrarAnimalActionPerformed

    private void btnListarAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAnimaisActionPerformed
        taSaida.setText("");
        for (Animal a : listaAnimais) {
            if (a instanceof Animal) {
                taSaida.append(a + "\n");
            }
        }
    }//GEN-LAST:event_btnListarAnimaisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int codExcluir = Integer.parseInt(JOptionPane.showInputDialog("Digite o código do animal a ser excluido: "));
        
        Animal petAux = buscarAnimal(codExcluir);
        
        if(petAux == null){
            JOptionPane.showMessageDialog(null, "Animal inexistente!");
        }else{
            listaAnimais.remove(petAux);
            taSaida.setText("Animal removido com sucesso!");
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int alteracao = Integer.parseInt(JOptionPane.showInputDialog("O que deseja alterar?" +
                "1 - Nome\n" + 
                "2 - Especie\n" + 
                "3 - Raça\n" + 
                "4 - sexo\n" + 
                "5 - Data de Nascimento\n" + 
                "6 - Peso\n" + 
                "7 - Dono\n\n" + 
                "Digite o número da opção:"
                ));
        
        if(alteracao >= 1 && alteracao <= 7){
            int codPet = Integer.parseInt(JOptionPane.showInputDialog("Digite o código do animal a ser alterado: "));
            Animal petAlterar = buscarAnimal(codPet);
            
            switch (alteracao){
                case 1:
                    String novoNome = JOptionPane.showInputDialog("Insira o novo nome");
                    petAlterar.setNome(novoNome);
                    break;
                case 2: 
                    String novaEspecie = JOptionPane.showInputDialog("Insira a nova espécie");
                    petAlterar.setEspecie(novaEspecie);
                    break;
                case 3: 
                    String novaRaca = JOptionPane.showInputDialog("Insira a nova raça");
                    petAlterar.setRaca(novaRaca);
                    break;
                case 4: 
                    String novoSexo = JOptionPane.showInputDialog("Insira o Sexo do animal");
                    petAlterar.setSexo(novoSexo);
                    break;
                case 5: 
                    String novaData = JOptionPane.showInputDialog("Insira a data de nascimento");
                    petAlterar.setDataNascimento(novaData);
                    break;
                case 6:
                    double novoPeso = Double.parseDouble(JOptionPane.showInputDialog("Insira o novo peso do animal"));
                    petAlterar.setPeso(novoPeso);
                    break;
                case 7:
                    int tutor = Integer.parseInt(JOptionPane.showInputDialog("Insira o Id do novo tutor do animal"));
                    Tutor novoTutor = buscarTutor(tutor);
                    if(novoTutor != null){
                        petAlterar.setDono(novoTutor);
                    }
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Opção inválida");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadastrarAnimal;
    private javax.swing.JButton btnListarAnimais;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
